### ISSUE TITLE
Deployment Strategy - For discussion

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#46]
# End goal
- deployment for Africa (WOFS) and Australia (some other products) based off the same code base (this repository?) 
- the difference between deployments across different environments are only differed by its deployed config files - is this possible? 
- longer-term deployment sustainment consideration

# Current wps deployment setup
```
    wpsConfig:
      path: /opt/config/wps
      filename: pywps.cfg
      image:
        # Docker Hub: https://hub.docker.com/r/geoscienceaustralia/dea-datakube-config
        # Source Repository: https://github.com/GeoscienceAustralia/dea-config
        registry: docker.io
        repository: geoscienceaustralia/dea-datakube-config
        tag: "1.4.10-unstable.24.g9c12bb3"
        pullPolicy: IfNotPresent
        src: /opt/dea-config/dev/services/wps/ows/pywps.cfg
```
I am not sure if this file is being used properly in wps deployment? I believe it might be redundant now with the amount of rework that has happened.

# Standard deployment pattern for reference
`datacube-ows` mounts it's environment specific config file on `/env/config`, the config file looks like this https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows/ows_cfg.py 
For the pod the following environment variable is required for `datacube-ows` to load it's config file
```
WMS_CONFIG_PATH: /env/config/ows_cfg.py
DATACUBE_OWS_CFG: "config.ows_cfg.ows_cfg"
```
